# Generated by Django 6.0.3 on 2026-04-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('exito', 'Realizada con éxito'), ('fallo', 'Fallida')], default='exito', max_length=10),
        ),
    ]
